"use client";
import { useActionState, useEffect, useMemo, useState } from "react";
import { createBookingAction, type BookingActionState } from "@/features/bookings/booking.actions";
import { ALLOWED_UPLOAD_TYPES, MAX_UPLOAD_COUNT, MAX_UPLOAD_SIZE } from "@/features/uploads/upload.validation";
import { SERVICE_METHODS } from "@/lib/constants";
import Link from "next/link";
import { formatCurrency } from "@/lib/presentation";

type Option = { id: string; label: string; type?: string; price?: number; description?: string; category?: string; detail?: string; duration?: number; supportedDeviceTypes?: string[] };
const steps = ["Device", "Services", "Problem", "Images", "Method", "Appointment", "Review", "Submit"];
const methodDetails={WALK_IN:["Walk in","Bring the device to our service location."],PICKUP:["Pickup","We collect the device from your address."],ON_SITE:["On-site","A technician visits the service address."]} as const;

export function BookingWizard({ devices, services, initialServiceId }: { devices: Option[]; services: Option[]; initialServiceId?: string }) {
  const [step, setStep] = useState(0);
  const [error, setError] = useState("");
  const [state, action, pending] = useActionState(createBookingAction, {} as BookingActionState);
  const [values, setValues] = useState({ deviceId: "", serviceIds: initialServiceId ? [initialServiceId] : [] as string[], problemTitle: "", problemDescription: "", symptoms: "", serviceMethod: "WALK_IN", preferredDate: "", preferredTimeSlot: "", addressLine1: "", addressLine2: "", city: "", state: "", country: "" });
  const [files, setFiles] = useState<File[]>([]);
  const previews = useMemo(() => files.map(file => ({ name: file.name, url: URL.createObjectURL(file) })), [files]);
  useEffect(() => () => previews.forEach(preview => URL.revokeObjectURL(preview.url)), [previews]);

  function validateCurrent() {
    if (step === 0 && !values.deviceId) return "Select a device.";
    if (step === 1 && !values.serviceIds.length) return "Select at least one service.";
    if (step === 2 && (values.problemTitle.trim().length < 3 || values.problemDescription.trim().length < 10)) return "Add a title and a description of at least 10 characters.";
    if (step === 4 && values.serviceMethod !== "WALK_IN" && (!values.addressLine1 || !values.city || !values.state || !values.country)) return "Complete the service address.";
    if (step === 5 && (!values.preferredDate || new Date(`${values.preferredDate}T00:00:00`) < new Date(new Date().setHours(0, 0, 0, 0)))) return "Choose today or a future date.";
    return "";
  }
  function next() { const issue = validateCurrent(); if (issue) return setError(issue); setError(""); setStep(current => Math.min(current + 1, steps.length - 1)); }
  function update(name: string, value: string) { setValues(current => ({ ...current, [name]: value, ...(name === "deviceId" ? { serviceIds: current.serviceIds.filter(id => { const service = services.find(item => item.id === id); return service && (!service.supportedDeviceTypes?.length || service.supportedDeviceTypes.includes(devices.find(device => device.id === value)?.type || "")); }) } : {}) })); }
  function selectFiles(list: FileList | null) {
    const selected = Array.from(list || []); const issue = selected.length > MAX_UPLOAD_COUNT ? `Choose no more than ${MAX_UPLOAD_COUNT} images.` : selected.find(file => file.size > MAX_UPLOAD_SIZE) ? "Each image must be 5 MB or smaller." : selected.find(file => !(ALLOWED_UPLOAD_TYPES as readonly string[]).includes(file.type)) ? "Only JPEG, PNG, and WebP images are supported." : "";
    setError(issue); setFiles(issue ? [] : selected);
  }
  const selectedDeviceOption = devices.find(device => device.id === values.deviceId),selectedDevice=selectedDeviceOption?.label;
  const compatibleServices = services.filter(service => !service.supportedDeviceTypes?.length || service.supportedDeviceTypes.includes(selectedDeviceOption?.type || ""));
  const selectedServices = services.filter(service => values.serviceIds.includes(service.id));
  const total = selectedServices.reduce((sum, service) => sum + (service.price || 0), 0);
  return <form action={action} className="booking-wizard">
    <div className="wizard-progress"><div><span>Step {step+1} of {steps.length}</span><strong>{steps[step]}</strong></div><div className="wizard-progress-track"><span style={{width:`${((step+1)/steps.length)*100}%`}}/></div><nav aria-label="Booking progress"><ol className="wizard-steps">{steps.map((label, index) => <li aria-current={index===step?"step":undefined} className={index === step ? "current" : index < step ? "done" : ""} key={label}><span aria-hidden="true">{index < step ? "✓" : index + 1}</span><span className="sr-only">Step {index+1}: </span>{label}</li>)}</ol></nav></div>
    <div className="wizard-panel">
      {step === 0 && <fieldset><legend>Select your device</legend><p className="wizard-intro">Which registered device needs maintenance? Only active devices without another open repair can be submitted.</p>{devices.length ? <><label className="field-label">Device <span className="required-marker" aria-hidden="true">*</span><select value={values.deviceId} onChange={event => update("deviceId", event.target.value)}><option value="">Choose a registered device</option>{devices.map(device => <option value={device.id} key={device.id}>{device.label}</option>)}</select><small>Select the exact device so its saved specifications follow the repair.</small></label>{selectedDeviceOption&&<div className="selection-preview"><span aria-hidden="true">▱</span><div><strong>{selectedDeviceOption.label}</strong><small>{selectedDeviceOption.detail||"Registered device"}</small></div><i>Selected</i></div>}</> : <div className="wizard-empty"><span aria-hidden="true">▱</span><strong>No active devices available</strong><p>Add a device first, then return here to create the repair request.</p><Link className="btn" href="/dashboard/devices/new">Add a device</Link></div>}</fieldset>}
      {step === 1 && <fieldset><legend>Select services</legend><p className="wizard-intro">Choose one or more services for {selectedDevice || "your device"}. The displayed total is a base-price estimate before diagnosis.</p>{compatibleServices.length?<><div className="service-choice-grid advanced">{compatibleServices.map(service => <label className={values.serviceIds.includes(service.id)?"selected":""} key={service.id}><input type="checkbox" checked={values.serviceIds.includes(service.id)} onChange={event => setValues(current => ({...current, serviceIds:event.target.checked ? [...current.serviceIds, service.id] : current.serviceIds.filter(id => id !== service.id)}))}/><span><small className="service-category-label">{service.category||"Maintenance service"}</small><strong>{service.label}</strong><em>{service.description||"Professional diagnosis and repair support."}</em><small>{service.duration?`About ${service.duration} minutes · `:""}Starting from {formatCurrency(service.price)}</small></span><i aria-hidden="true">✓</i></label>)}</div><div className="selection-total"><span>{selectedServices.length} service{selectedServices.length===1?"":"s"} selected</span><strong>{formatCurrency(total)} base estimate</strong></div></>:<div className="wizard-empty"><strong>No services are available for this device yet</strong><p>Choose another device or contact support for help.</p></div>}</fieldset>}
      {step === 2 && <fieldset><legend>Describe the problem</legend><p className="wizard-intro">Detailed information helps the technician reproduce the fault and prepare an accurate diagnosis.</p><div className="form-stack"><label>Problem title <span className="required-marker" aria-hidden="true">*</span><input value={values.problemTitle} onChange={e => update("problemTitle", e.target.value)} maxLength={120} placeholder="For example, laptop will not turn on"/><small>Use a short, specific summary · {values.problemTitle.length}/120</small></label><label>Description <span className="required-marker" aria-hidden="true">*</span><textarea value={values.problemDescription} onChange={e => update("problemDescription", e.target.value)} maxLength={3000} rows={6} placeholder="When did it start? What happens? What have you already tried?"/><small>Minimum 10 characters · {values.problemDescription.length}/3000</small></label><label>Symptoms<input value={values.symptoms} onChange={e => update("symptoms", e.target.value)} placeholder="No power, unusual noise, blue screen"/><small>Separate multiple symptoms with commas.</small></label></div><div className="problem-prompts"><strong>Useful details to include</strong><ul><li>When the problem started</li><li>Any error message or unusual sound</li><li>Recent updates, drops, spills, or repairs</li></ul></div></fieldset>}
      {step === 4 && <fieldset><legend>Choose service method</legend><p className="wizard-intro">Choose how the device will reach the repair team.</p><div className="method-choice-grid">{SERVICE_METHODS.map(method=>{const[label,detail]=methodDetails[method];return <label className={values.serviceMethod===method?"selected":""} key={method}><input type="radio" checked={values.serviceMethod===method} onChange={()=>update("serviceMethod",method)}/><span><strong>{label}</strong><small>{detail}</small></span><i aria-hidden="true">✓</i></label>})}</div>{values.serviceMethod !== "WALK_IN" && <div className="address-section"><h3>Service address</h3><div className="address-grid"><label>Address line 1 <span className="required-marker" aria-hidden="true">*</span><input value={values.addressLine1} onChange={e => update("addressLine1", e.target.value)} placeholder="Street address"/></label><label>Address line 2<input value={values.addressLine2} onChange={e => update("addressLine2", e.target.value)} placeholder="Apartment, suite, or landmark"/></label><label>City <span className="required-marker" aria-hidden="true">*</span><input value={values.city} onChange={e => update("city", e.target.value)}/></label><label>State <span className="required-marker" aria-hidden="true">*</span><input value={values.state} onChange={e => update("state", e.target.value)}/></label><label>Country <span className="required-marker" aria-hidden="true">*</span><input value={values.country} onChange={e => update("country", e.target.value)}/></label></div></div>}</fieldset>}
      {step === 5 && <fieldset><legend>Select date and time</legend><p className="wizard-intro">Choose your preferred appointment window. The team will confirm the final schedule.</p><div className="appointment-grid"><label>Preferred date <span className="required-marker" aria-hidden="true">*</span><input type="date" min={new Date().toISOString().slice(0,10)} value={values.preferredDate} onChange={e => update("preferredDate", e.target.value)}/></label><label>Preferred time slot<input list="booking-time-slots" value={values.preferredTimeSlot} onChange={e => update("preferredTimeSlot", e.target.value)} maxLength={60} placeholder="Choose or enter a time window"/><datalist id="booking-time-slots"><option value="09:00-11:00"/><option value="11:00-13:00"/><option value="13:00-15:00"/><option value="15:00-17:00"/></datalist></label></div><div className="appointment-note"><strong>Scheduling note</strong><p>This is a preference, not a confirmed appointment. You will receive an update after the request is reviewed.</p></div></fieldset>}
      {step === 6 && <section className="booking-review"><h2>Review your booking</h2><p className="wizard-intro">Check every section before continuing. Use Back to correct any information.</p><dl><div><dt>Device</dt><dd>{selectedDevice}<span>{selectedDeviceOption?.detail}</span></dd></div><div><dt>Services</dt><dd>{selectedServices.map(service => service.label).join(", ")}</dd></div><div><dt>Problem</dt><dd><strong>{values.problemTitle}</strong><span>{values.problemDescription}</span></dd></div><div><dt>Symptoms</dt><dd>{values.symptoms||"None provided"}</dd></div><div><dt>Images</dt><dd>{files.length ? `${files.length} attached` : "No images attached"}</dd></div><div><dt>Service method</dt><dd>{methodDetails[values.serviceMethod as keyof typeof methodDetails][0]}</dd></div>{values.serviceMethod!=="WALK_IN"&&<div><dt>Service address</dt><dd>{[values.addressLine1,values.addressLine2,values.city,values.state,values.country].filter(Boolean).join(", ")}</dd></div>}<div><dt>Preferred appointment</dt><dd>{values.preferredDate} {values.preferredTimeSlot||"No time specified"}</dd></div></dl><div className="estimate-panel"><span>Base-price estimate<small>Final pricing may change after diagnosis and quotation.</small></span><strong>{formatCurrency(total)}</strong></div></section>}
      {step === 7 && <section className="submit-panel"><span className="submit-check" aria-hidden="true">✓</span><h2>Ready to send your request</h2><p>Your details will be validated securely. You can track the booking and receive updates from your dashboard.</p><div className="submit-summary"><span>{selectedDevice}</span><span>{selectedServices.length} service{selectedServices.length===1?"":"s"}</span><strong>{formatCurrency(total)} estimate</strong></div><button className="btn" disabled={pending}>{pending ? "Submitting your booking…" : "Submit booking"}</button></section>}
    </div>
    <fieldset hidden={step !== 3} className="wizard-panel upload-step"><legend>Add optional images</legend><p className="wizard-intro">Photos can help the technician understand physical damage or error messages.</p><label className="upload-dropzone"><span aria-hidden="true">↑</span><strong>Choose problem images</strong><small>JPEG, PNG, or WebP · Up to five files · 5 MB each</small><input name="images" aria-label="Problem images" type="file" accept={ALLOWED_UPLOAD_TYPES.join(",")} multiple onChange={e => selectFiles(e.target.files)}/></label>{previews.length>0&&<div className="preview-grid">{previews.map(preview => <figure key={preview.url}><img src={preview.url} alt={`Preview of ${preview.name}`}/><figcaption>{preview.name}</figcaption></figure>)}</div>}</fieldset>
    {Object.entries(values).map(([name, value]) => Array.isArray(value) ? value.map(item => <input key={`${name}-${item}`} type="hidden" name={name} value={item}/>) : <input key={name} type="hidden" name={name} value={value}/>)}
    {(error || state.error) && <p className="error" role="alert">{error || state.error}</p>}
    <div className="wizard-actions">{step > 0 ? <button type="button" className="btn secondary" disabled={pending} onClick={() => {setError("");setStep(current => current - 1)}}>← Back</button>:<span/>}{step < 7 && <button type="button" className="btn" onClick={next} disabled={step === 0 && !devices.length}>Next →</button>}</div>
  </form>;
}
