import"server-only";import mongoose from"mongoose";import{connectDB}from"@/lib/db";import{Assignment}from"@/models/Assignment";import{TechnicianProfile}from"@/models/TechnicianProfile";import{User}from"@/models/User";import{Booking}from"@/models/Booking";import{BusinessRuleError,NotFoundError,AuthorizationError,ConflictError}from"@/lib/errors";import{transitionBooking}from"@/features/bookings/status.service";import{Notification}from"@/models/Notification";import{AuditLog}from"@/models/AuditLog";import{canAcceptAssignment}from"./assignment.rules";
export async function assignTechnician(bookingId:string,technicianId:string,adminId:string){await connectDB();const [booking,user,profile]=await Promise.all([Booking.findById(bookingId),User.findOne({_id:technicianId,role:"TECHNICIAN",status:"ACTIVE"}),TechnicianProfile.findOne({userId:technicianId})]);if(!booking||booking.status!=="RECEIVED")throw new BusinessRuleError("Only received bookings can be assigned");if(!user||!profile)throw new NotFoundError("Active technician not found");if(profile.availabilityStatus!=="AVAILABLE"||profile.activeJobCount>=profile.maximumActiveJobs)throw new BusinessRuleError("Technician is unavailable or at workload limit");const assignment=await Assignment.create({bookingId,technicianId,assignedBy:adminId});await TechnicianProfile.updateOne({_id:profile.id},{$inc:{activeJobCount:1}});await transitionBooking(bookingId,"ASSIGNED",adminId,`Assigned to ${user.firstName}`);await Notification.insertMany([{userId:technicianId,bookingId,type:"ASSIGNED",title:"New assignment",message:`You were assigned ${booking.reference}.`},{userId:booking.customerId,bookingId,type:"ASSIGNED",title:"Technician assigned",message:`A technician was assigned to ${booking.reference}.`}]);return assignment}
export async function assertAssigned(bookingId:string,technicianId:string){if(!mongoose.isValidObjectId(bookingId)||!await Assignment.exists({bookingId,technicianId,status:"ACTIVE"}))throw new AuthorizationError("Job is not assigned to you")}
export async function assertAcceptedAssignment(bookingId:string,technicianId:string){if(!mongoose.isValidObjectId(bookingId)||!await Assignment.exists({bookingId,technicianId,status:"ACTIVE",acceptedAt:{$exists:true}}))throw new BusinessRuleError("Accept this assignment before starting work")}
export async function acceptAssignment(bookingId:string,technicianId:string){
  await connectDB();
  if(!mongoose.isValidObjectId(bookingId))throw new NotFoundError("Assignment not found");
  const [assignment,booking]=await Promise.all([Assignment.findOne({bookingId,technicianId,status:"ACTIVE"}),Booking.findById(bookingId)]);
  if(!assignment||!booking)throw new AuthorizationError("Job is not assigned to you");
  if(assignment.acceptedAt)throw new ConflictError("Assignment has already been accepted");
  if(!canAcceptAssignment(assignment.status,assignment.acceptedAt,booking.status))throw new BusinessRuleError("This assignment can no longer be accepted");
  const acceptedAt=new Date();
  const accepted=await Assignment.findOneAndUpdate({_id:assignment.id,technicianId,status:"ACTIVE",acceptedAt:{$exists:false}},{$set:{acceptedAt}},{new:true});
  if(!accepted)throw new ConflictError("Assignment has already been accepted");
  try{await AuditLog.create({actorId:technicianId,action:"ASSIGNMENT_ACCEPTED",entityType:"Assignment",entityId:accepted.id,summary:{bookingId,acceptedAt}})}catch(error){await Assignment.updateOne({_id:accepted.id,acceptedAt},{$unset:{acceptedAt:1}});throw error}
  try{await Notification.create({userId:booking.customerId,bookingId,type:"ASSIGNMENT_ACCEPTED",title:"Technician accepted your repair",message:`Work on ${booking.reference} has been accepted by the assigned technician.`})}catch(error){console.error("Assignment accepted but customer notification failed",error)}
  return accepted;
}
