import "server-only";
import { connectDB } from "@/lib/db";
import { assertAcceptedAssignment, assertAssigned } from "@/features/assignments/assignment.service";
import { transitionBooking } from "@/features/bookings/status.service";
import { BusinessRuleError, NotFoundError } from "@/lib/errors";
import { Booking } from "@/models/Booking";
import { Diagnosis } from "@/models/Diagnosis";
import { Notification } from "@/models/Notification";
import { Assignment } from "@/models/Assignment";
import { Quotation } from "@/models/Quotation";
import { diagnosisDraftSchema, diagnosisRevisionRequestSchema, diagnosisSubmissionSchema } from "./diagnosis.validation";

async function requireDiagnosisAccess(bookingId:string,technicianId:string){await connectDB();await assertAssigned(bookingId,technicianId);await assertAcceptedAssignment(bookingId,technicianId);const booking=await Booking.findById(bookingId);if(!booking)throw new NotFoundError("Booking not found");return booking}
export async function startDiagnosis(bookingId:string,technicianId:string){const booking=await requireDiagnosisAccess(bookingId,technicianId);if(booking.status!=="ASSIGNED")throw new BusinessRuleError("Diagnosis can start only for an assigned booking");return transitionBooking(bookingId,"DIAGNOSING",technicianId,"Diagnosis started")}
export async function saveDiagnosisDraft(bookingId:string,technicianId:string,input:unknown){const data=diagnosisDraftSchema.parse(input),booking=await requireDiagnosisAccess(bookingId,technicianId);if(booking.status!=="DIAGNOSING")throw new BusinessRuleError("Diagnosis drafts can be saved only while diagnosing");const draft=await Diagnosis.findOne({bookingId,technicianId,status:"DRAFT"}).select("+internalNotes");if(draft){draft.set(data);return draft.save()}const latest:any=await Diagnosis.findOne({bookingId}).sort({revision:-1}).select("revision").lean();return Diagnosis.create({...data,bookingId,technicianId,revision:(latest?.revision||0)+1,status:"DRAFT"})}
export async function submitDiagnosis(bookingId:string,technicianId:string,input:unknown){const data=diagnosisSubmissionSchema.parse(input),booking=await requireDiagnosisAccess(bookingId,technicianId);if(booking.status!=="DIAGNOSING")throw new BusinessRuleError("Diagnosis can be submitted only while diagnosing");let diagnosis=await Diagnosis.findOne({bookingId,technicianId,status:"DRAFT"}).select("+internalNotes");let created=false;if(!diagnosis){const latest:any=await Diagnosis.findOne({bookingId}).sort({revision:-1}).select("revision").lean();diagnosis=new Diagnosis({...data,bookingId,technicianId,revision:(latest?.revision||0)+1});created=true}else diagnosis.set(data);diagnosis.status="SUBMITTED";diagnosis.submittedAt=new Date();await diagnosis.save();try{await transitionBooking(bookingId,"AWAITING_APPROVAL",technicianId,`Diagnosis revision ${diagnosis.revision} submitted`)}catch(error){if(created)await Diagnosis.deleteOne({_id:diagnosis.id,status:"SUBMITTED"});else{diagnosis.status="DRAFT";diagnosis.submittedAt=undefined;await diagnosis.save()}throw error}try{await Notification.create({userId:booking.customerId,bookingId,type:"DIAGNOSIS_READY",title:"Diagnosis ready",message:`The diagnosis for ${booking.reference} is ready for review.`})}catch(error){console.error("Diagnosis submitted but notification failed",error)}return diagnosis}

export async function requestDiagnosisRevision(bookingId:string,adminId:string,input:unknown){const{reason}=diagnosisRevisionRequestSchema.parse(input);await connectDB();const[booking,assignment,latest,existingDraft]=await Promise.all([Booking.findById(bookingId),Assignment.findOne({bookingId,status:"ACTIVE",acceptedAt:{$exists:true}}).lean(),Diagnosis.findOne({bookingId,status:{$in:["SUBMITTED","APPROVED"]}}).sort({revision:-1}).select("+internalNotes"),Diagnosis.exists({bookingId,status:"DRAFT"})]);if(!booking)throw new NotFoundError("Booking not found");if(booking.status!=="AWAITING_APPROVAL")throw new BusinessRuleError("A diagnosis revision can be requested only while awaiting approval");if(!assignment)throw new BusinessRuleError("An accepted active technician assignment is required");if(!latest)throw new BusinessRuleError("A submitted diagnosis is required");if(existingDraft)throw new BusinessRuleError("A diagnosis revision is already in progress");const previous=await Quotation.find({bookingId,status:"PENDING"}).select("_id").lean(),draft=await Diagnosis.create({bookingId,technicianId:(assignment as any).technicianId,revision:latest.revision+1,observedSymptoms:latest.observedSymptoms,faultCategory:latest.faultCategory,faultDescription:latest.faultDescription,recommendedAction:latest.recommendedAction,requiredParts:latest.requiredParts,internalNotes:latest.internalNotes,customerSummary:latest.customerSummary,status:"DRAFT"});try{if(previous.length)await Quotation.updateMany({_id:{$in:previous.map(item=>item._id)},status:"PENDING"},{$set:{status:"REPLACED"}});await transitionBooking(bookingId,"DIAGNOSING",adminId,`Diagnosis revision ${draft.revision} requested: ${reason}`)}catch(error){await Diagnosis.deleteOne({_id:draft.id,status:"DRAFT"});if(previous.length)await Quotation.updateMany({_id:{$in:previous.map(item=>item._id)},status:"REPLACED"},{$set:{status:"PENDING"}});throw error}try{await Notification.insertMany([{userId:(assignment as any).technicianId,bookingId,type:"DIAGNOSIS_REVISION_REQUESTED",title:"Diagnosis revision requested",message:`Revise the diagnosis for ${booking.reference}: ${reason}`},{userId:booking.customerId,bookingId,type:"DIAGNOSIS_REVISION_REQUESTED",title:"Diagnosis is being revised",message:`A new diagnosis revision was requested for ${booking.reference}.`}])}catch(error){console.error("Diagnosis revision requested but notification failed",error)}return draft}
